markdown: kramdown
highlighter: rouge

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

#Global vars
asset-img-path: /img/assets/
asset-path: /assets/
asset-download-path: /downloads/assets/

#artist-img-path: /img/artists/

#external-download-path: http://brackeys.com/devassets/

#Featured
#featured-banner: 2D Mega Pack
#featured-two-thirds: Modern Weapons
#featured-one-third: Desert Environment

#home-banner: Sci-Fi Weapons

#home-one-third-1: 2D Mega Pack
#home-one-third-2: Western Props Pack
#home-one-third-3: Sci-Fi Vehicles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"
  - scope:
      type: assets
    values:
      layout: asset-view
      banner-img: Banner.jpg
      two-thirds-img: TwoThirds.jpg
      one-third-img: OneThird.jpg
      priority: 10
      show: true
      is-for-course: false
      file-type: .zip


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true
  assets:
    output: true
    permalink: /:collection/:title/
  artists:

name: Rudra's Yard • Game Designer | Programmer
description: Rudra Nil Basu- Personal portfolio
url: https://jekyllrb.com

twitter:
  username: RudraNilBasu

logo: /img/final_1.png

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md
