# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rudra's Yard
description: > # this means to ignore newlines until "baseurl:"
  Game Designer, Programmer
  Rudra Nil Basu - Personal portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rudranilbasu.github.io" # the base hostname & protocol for your site
twitter_username: RudraNilBasu
github_username:  RudraNilBasu

#Global vars
asset-img-path: /img/assets/
asset-path: /assets/
asset-download-path: /downloads/assets/

artist-img-path: /img/artists/

external-download-path: https://brackeys.com/devassets/

#Snipcart
snipcart-api-key: NjY3ZTgwNGQtNjM2Ni00YjUzLWExZGYtNjRjNGRlNzcxZmIwNjM2MTE0NTA4MDE5ODI4MDU5
#OLD TEST KEY
#M2RjMTc3NGUtYjNhMC00NTFlLWJjN2ItOTBkNGNkNDRjN2U2NjM2MTE0NTA4MDE5ODI4MDU5

#Featured
#2D Mega Pack
#Sci-Fi Weapons
#Desert Environment
featured-banner: Supervision
featured-two-thirds: Followed
featured-one-third: Chalk

home-banner: General Textures

home-one-third-1: 2D Mega Pack
home-one-third-2: Modern Weapons
home-one-third-3: Sci-Fi Vehicles

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-sitemap

sass:
  sass_dir: css/_sass
  style: compressed

collections:
  assets:
    output: true
    permalink: /:collection/:title/
  artists:

defaults:
  - scope:
      type: assets
    values:
      layout: asset-view
      banner-img: Banner.jpg
      two-thirds-img: TwoThirds.jpg
      one-third-img: OneThird.jpg
      priority: 10
      show: true
      is-for-course: false
      file-type: .zip
